In [ ]:
import pandas as pd

In [ ]:
import sys
print(sys.executable)

/Users/louiserigny/opt/anaconda3/envs/PythonTutorial/bin/python3

In [ ]:
import os
print(os.getcwd())  # Check the current working directory
os.chdir('/Users/louiserigny/Desktop/home/medtimeline/medtimeline/')

/Users/louiserigny/Desktop/home/medtimeline/medtimeline

In [1]:
from medtimeline.Med import TimelineGenerator
config_file_path = '/Users/louiserigny/Desktop/home/medtimeline/medtimeline/config.json'
timeline_generator = TimelineGenerator(config_file_path)

In [2]:
from medtimeline.Med import ProceduresTimelineGenerator
proc_timeline_generator=ProceduresTimelineGenerator(config_file_path)

In [3]:
from medtimeline.Med import PatientJourneyGenerator
patient_journey=PatientJourneyGenerator(config_file_path)

In [4]:
config_file_path = '/Users/louiserigny/Desktop/home/medtimeline/medtimeline/config.json'
proc_timelines = patient_journey.GenerateFullJourney()
proc_timelines

Day,admission_id,28,365,367,425,426,427,520,521,771,...,161,163,180,182,518,527,675,683,697,703
0,PR-00000022_1,"[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, [R298, I340, Z918], nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[[173196.0], nan, nan, nan]","[[173196.0, 173196.0], [CREATHigh], nan, nan]","[nan, nan, nan, nan]",...,"[nan, nan, nan, [LAB293]]","[nan, nan, nan, [IMG34, PFT19]]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, [LAB3090]]","[nan, nan, nan, [ECH110, PFT19]]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]"
1,PR-00000022_2,"[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, [R298, I340, Z918], nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[[173196.0], nan, nan, nan]","[[173196.0, 173196.0], [CREATHigh], nan, nan]","[nan, nan, nan, nan]",...,"[nan, nan, nan, [LAB293]]","[nan, nan, nan, [IMG34, PFT19]]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, [LAB3090]]","[nan, nan, nan, [ECH110, PFT19]]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]"
2,PR-00000022_3,"[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, [R298, I340, Z918], nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[[173196.0], nan, nan, nan]","[[173196.0, 173196.0], [CREATHigh], nan, nan]","[nan, nan, nan, nan]",...,"[nan, nan, nan, [LAB293]]","[nan, nan, nan, [IMG34, PFT19]]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, [LAB3090]]","[nan, nan, nan, [ECH110, PFT19]]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]","[nan, nan, nan, nan]"
3,PR-00000034_1,"[nan, nan, nan, nan, nan]","[[181004.0], nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]",...,"[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]"
4,PR-00000035_1,"[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[[184704.0], nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]",...,"[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]"
5,PR-00000076_1,"[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[[17762.0], nan, nan, nan, nan]","[[18877.0], nan, nan, [Z941], nan]","[[15797.0], nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]",...,"[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, [CON157]]","[nan, nan, nan, nan, [P0C118]]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]"
6,PR-00000076_2,"[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[[17762.0], nan, nan, nan, nan]","[[18877.0], nan, nan, [Z941], nan]","[[15797.0], nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]",...,"[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, [CON157]]","[nan, nan, nan, nan, [P0C118]]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]"
7,PR-00000076_3,"[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[[17762.0], nan, nan, nan, nan]","[[18877.0], nan, nan, [Z941], nan]","[[15797.0], nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]",...,"[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, [CON157]]","[nan, nan, nan, nan, [P0C118]]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]"
8,PR-00000083_1,"[[478137.0], nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]",...,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"
9,PR-00000083_2,"[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[[478137.0], nan, nan, nan, nan]",...,"[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan]","[nan, nan, nan, nan, [IMG154, PFT49]]","[nan, nan, nan, nan, [U201]]","[nan, nan, nan, nan, [ECH110]]","[nan, nan, nan, nan, [ECH204, PFT53]]"

In [ ]:
diag_timelines = timeline_generator.generate_diagnoses_timeline()
diag_timelines

Day,admission_id,27,31,347,367,370,426,430,770,774
0,PR-00000022_1,NaN,NaN,NaN,"[R298, I340, Z918]",NaN,NaN,NaN,NaN,NaN
1,PR-00000022_2,NaN,NaN,NaN,"[R298, I340, Z918]",NaN,NaN,NaN,NaN,NaN
2,PR-00000022_3,NaN,NaN,NaN,"[R298, I340, Z918]",NaN,NaN,NaN,NaN,NaN
3,PR-00000034_1,NaN,NaN,NaN,NaN,[H55],NaN,NaN,NaN,NaN
4,PR-00000035_1,NaN,NaN,[I270],NaN,NaN,NaN,NaN,NaN,NaN
5,PR-00000076_1,NaN,NaN,NaN,NaN,NaN,[Z941],"[T862, Z958]",NaN,NaN
6,PR-00000076_2,NaN,NaN,NaN,NaN,NaN,[Z941],"[T862, Z958]",NaN,NaN
7,PR-00000076_3,NaN,NaN,NaN,NaN,NaN,[Z941],"[T862, Z958]",NaN,NaN
8,PR-00000083_1,[I500],[Q871],NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,PR-00000083_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[I500],[Q871]

In [ ]:
labs_timelines = timeline_generator.generate_labs_timeline()
labs_timelines

Day,admission_id,60,77,98,121,123,159,213,521,679,708
0,PR-00000022_1,NaN,NaN,[UREANormal],NaN,NaN,[CREATLow],NaN,[CREATHigh],NaN,NaN
1,PR-00000022_2,NaN,NaN,[UREANormal],NaN,NaN,[CREATLow],NaN,[CREATHigh],NaN,NaN
2,PR-00000022_3,NaN,NaN,[UREANormal],NaN,NaN,[CREATLow],NaN,[CREATHigh],NaN,NaN
3,PR-00000034_1,[CANormal],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PR-00000035_1,NaN,[CAHigh],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,PR-00000076_1,NaN,NaN,NaN,[K1Low],[K1Normal],NaN,[NA1High],NaN,NaN,NaN
6,PR-00000076_2,NaN,NaN,NaN,[K1Low],[K1Normal],NaN,[NA1High],NaN,NaN,NaN
7,PR-00000076_3,NaN,NaN,NaN,[K1Low],[K1Normal],NaN,[NA1High],NaN,NaN,NaN
8,PR-00000083_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[NA1Low],[K1Normal]

In [ ]:
surg_timelines = timeline_generator.generate_surgery_timeline()
surg_timelines

Day,admission_id,200,229,233,330,339,351,360
0,PR-00000034_1,NaN,NaN,[K04.9],NaN,NaN,NaN,NaN
1,PR-00000035_1,[nan],NaN,NaN,NaN,NaN,NaN,NaN
2,PR-00000076_1,NaN,[K58.9],NaN,NaN,NaN,[K58.9],[T05.1]
3,PR-00000076_2,NaN,[K58.9],NaN,NaN,NaN,[K58.9],[T05.1]
4,PR-00000076_3,NaN,[K58.9],NaN,NaN,NaN,[K58.9],[T05.1]
5,PR-00000083_2,NaN,NaN,NaN,[T16.2],[K17.1],NaN,NaN

In [ ]:
med_timelines = timeline_generator.generate_medication_timeline()
med_timelines

Day,admission_id,28,365,367,425,426,427,520,521,771
0,PR-00000022_1,NaN,NaN,NaN,NaN,NaN,NaN,[173196.0],"[173196.0, 173196.0]",NaN
1,PR-00000022_2,NaN,NaN,NaN,NaN,NaN,NaN,[173196.0],"[173196.0, 173196.0]",NaN
2,PR-00000022_3,NaN,NaN,NaN,NaN,NaN,NaN,[173196.0],"[173196.0, 173196.0]",NaN
3,PR-00000034_1,NaN,[181004.0],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PR-00000035_1,NaN,NaN,[184704.0],NaN,NaN,NaN,NaN,NaN,NaN
5,PR-00000076_1,NaN,NaN,NaN,[17762.0],[18877.0],[15797.0],NaN,NaN,NaN
6,PR-00000076_2,NaN,NaN,NaN,[17762.0],[18877.0],[15797.0],NaN,NaN,NaN
7,PR-00000076_3,NaN,NaN,NaN,[17762.0],[18877.0],[15797.0],NaN,NaN,NaN
8,PR-00000083_1,[478137.0],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,PR-00000083_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[478137.0]